{
 "title": "Ganesha (local)",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total request rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ganesha:nfs_requests:rate1m", "legendFormat": "{{ operation}}" }
   ]
  },
  {
   "title": "Mean (50%) latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "ganesha:latency_ms_percentile:rate1m{percentile=\"50\"}",
     "legendFormat": "{{ operation}}"
    }
   ]
  },
  {
   "title": "Total throughput (Bytes/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "ganesha:nfs_bytes_transferred:rate1m",
     "legendFormat": "{{ operation}}"
    }
   ]
  },
  {
   "title": "Metadata cache hit ratios",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ganesha:mdcache_cache_hit_ratio:rate1m * 100",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "1% latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "ganesha:latency_ms_percentile:rate1m{percentile=\"1\"}",
       "legendFormat": "{{ operation}}"
      }
     ]
    },
    {
     "title": "90% latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "ganesha:latency_ms_percentile:rate1m{percentile=\"90\"}",
       "legendFormat": "{{ operation}}"
      }
     ]
    },
    {
     "title": "Mean (50%) latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "ganesha:latency_ms_percentile:rate1m{percentile=\"50\"}",
       "legendFormat": "{{ operation}}"
      }
     ]
    },
    {
     "title": "95% latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "ganesha:latency_ms_percentile:rate1m{percentile=\"95\"}",
       "legendFormat": "{{ operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency distributions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read latency distribution",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "ganesha:latency_ms_percentile:rate1m{operation=\"read\"}",
       "legendFormat": "{{ percentile }}%"
      }
     ]
    },
    {
     "title": "Write latency distribution",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "ganesha:latency_ms_percentile:rate1m{operation=\"write\"}",
       "legendFormat": "{{ percentile }}%"
      }
     ]
    },
    {
     "title": "Getattr latency distribution",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "ganesha:latency_ms_percentile:rate1m{operation=\"getattr\"}",
       "legendFormat": "{{ percentile }}%"
      }
     ]
    },
    {
     "title": "Lookup latency distribution",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "ganesha:latency_ms_percentile:rate1m{operation=\"lookup\"}",
       "legendFormat": "{{ percentile }}%"
      }
     ]
    },
    {
     "title": "Access latency distribution",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "ganesha:latency_ms_percentile:rate1m{operation=\"access\"}",
       "legendFormat": "{{ percentile }}%"
      }
     ]
    }
   ]
  },
  {
   "title": "Request / response sizes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    { "title": "Reads", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 20 }, "options": { "content": " " } },
    { "title": "Writes", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 12, "y": 20 }, "options": { "content": " " } },
    {
     "title": "NFS read response size heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "ganesha:nfs_response_size_bytes:rate1m{operation=\"read\"}",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "NFS write request size heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "ganesha:nfs_request_size_bytes:rate1m{operation=\"write\"}",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "NFS read request size heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "ganesha:nfs_request_size_bytes:rate1m{operation=\"read\"}",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Errors / second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ganesha:nfs_errors:rate1m{status!~\"NFS3_OK|NFS4_OK\"}",
       "legendFormat": "{{ version }} {{ operation }} {{ status }}"
      }
     ]
    },
    {
     "title": "Error rate (%)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "ganesha:nfs_errors:ratio:rate1m",
       "legendFormat": "{{ version }} {{ operation }}"
      }
     ]
    },
    {
     "title": "Total error count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ganesha:nfs_errors:sum{status!~\"NFS3_OK|NFS4_OK\"}",
       "legendFormat": "{{ version }} {{ operation }} {{ status }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Per export metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total request rate per export",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ganesha:nfs_requests_by_export:sum:rate1m",
       "legendFormat": "{{ export}}"
      }
     ]
    },
    {
     "title": "Cache hit ratio per export [ getattr ]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "ganesha:mdcache_cache_hit_ratio_by_export:rate1m{operation=\"getattr\"} * 100",
       "legendFormat": "{{ export }}"
      }
     ]
    },
    {
     "title": "Read throughput per export (Bytes/s)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "ganesha:nfs_bytes_transferred_by_export:rate1m{operation=\"read\"}",
       "legendFormat": "{{ export }}"
      }
     ]
    },
    {
     "title": "Cache hit ratio per export [ lookup ]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "ganesha:mdcache_cache_hit_ratio_by_export:rate1m{operation=\"lookup\"} * 100",
       "legendFormat": "{{ export }}"
      }
     ]
    },
    {
     "title": "Write throughput per export (Bytes/s)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "ganesha:nfs_bytes_transferred_by_export:rate1m{operation=\"write\"}",
       "legendFormat": "{{ export }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Per export latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mean (50%) read latency per export",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "ganesha:latency_ms_by_export_percentile:rate1m{percentile=\"50\", operation=\"read\"}",
       "legendFormat": "{{ export }}"
      }
     ]
    },
    {
     "title": "Mean (50%) latency per export (all operations)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "ganesha:latency_ms_by_export_percentile:rate1m{percentile=\"50\"}",
       "legendFormat": "{{ operation }} {{ export }}"
      }
     ]
    },
    {
     "title": "90% read latency per export",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "ganesha:latency_ms_by_export_percentile:rate1m{percentile=\"90\", operation=\"read\"}",
       "legendFormat": "{{ export }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Other metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPCs in flight",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "ganesha:rpcs_in_flight", "legendFormat": "rpcs" }
     ]
    },
    {
     "title": "Worker threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "ganesha:worker_threads", "legendFormat": "{{ label }}" }
     ]
    },
    {
     "title": "Rate of RPCs received / completed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "ganesha:rpcs_received:rate1m", "legendFormat": "received" },
      { "expr": "ganesha:rpcs_completed:rate1m", "legendFormat": "completed" }
     ]
    }
   ]
  }
 ]
}