/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "cqos.h"

bool_t
xdr_int32_t (XDR *xdrs, int32_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_uint32_t (XDR *xdrs, uint32_t *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_int64_t (XDR *xdrs, int64_t *objp)
{
	register int32_t *buf;

	 if (!xdr_quad_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_uint64_t (XDR *xdrs, uint64_t *objp)
{
	register int32_t *buf;

	 if (!xdr_u_quad_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cluster_qos_msg (XDR *xdrs, cluster_qos_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_cqos_cmd_type_t (xdrs, &objp->cqos_cmd))
		 return FALSE;
	 if (!xdr_int32_t (xdrs, &objp->cqos_ops))
		 return FALSE;
	 if (!xdr_uint16_t (xdrs, &objp->export_id))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->export_rbw))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->export_wbw))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->export_riops))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->export_wiops))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->client_rbw))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->client_wbw))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->client_riops))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->client_wiops))
		 return FALSE;
	 if (!xdr_sockaddr_t (xdrs, &objp->node_addr))
		 return FALSE;
	 if (!xdr_sockaddr_t (xdrs, &objp->client_addr))
		 return FALSE;
	return TRUE;
}
