/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "nfs_core.h"
#include "gsh_rpc.h"
#include "tsm.h"

bool xdr_tsm_export_info(XDR *xdrs, tsm_export_info *objp)
{
	if (!xdr_opaque(xdrs, (char *)objp, sizeof(tsm_export_info)))
		return false;

	return true;
}

bool xdr_tsm_state_open(XDR *xdrs, tsm_state_open *objp)
{
	if (!xdr_opaque(xdrs, (char *)objp, sizeof(struct tsm_state_open)))
		return false;
	return true;
}

bool xdr_tsm_state_lock(XDR *xdrs, tsm_state_lock *objp)
{
	if (!xdr_opaque(xdrs, (char *)objp, sizeof(struct tsm_state_lock)))
		return false;
	return true;
}
bool xdr_tsm_state_deleg(XDR *xdrs, tsm_state_deleg *objp)
{
	if (!xdr_opaque(xdrs, (char *)objp, sizeof(struct tsm_state_deleg)))
		return false;
	return true;
}
bool xdr_sockaddr_tsm(XDR *xdrs, sockaddr_t *objp)
{
	if (!xdr_opaque(xdrs, (char *)objp, sizeof(sockaddr_t)))
		return false;
	return true;
}

bool xdr_tsm_rpc_info(XDR *xdrs, tsm_rpc_info *objp)
{
	if (!xdr_uint32_t(xdrs, &objp->msg_type))
		return false;
	if (!xdr_uint64_t(xdrs, &objp->msg_id))
		return false;
	if (!xdr_uint64_t(xdrs, &objp->fsid_maj))
		return false;
	if (!xdr_uint64_t(xdrs, &objp->fsid_min))
		return false;
	if (!xdr_uint64_t(xdrs, &objp->fileid))
		return false;
	if (!xdr_uint16_t(xdrs, &objp->rec_type))
		return false;
	if (!xdr_tsm_state_open(xdrs, &objp->open_info))
		return false;
	if (!xdr_tsm_state_lock(xdrs, &objp->lock_info))
		return false;
	if (!xdr_tsm_state_deleg(xdrs, &objp->deleg_info))
		return false;
	if (!xdr_sockaddr_tsm(xdrs, &objp->source_addr))
		return false;
	/*janimesh adding encoding*/
	if (!xdr_sockaddr_tsm(xdrs, &objp->primary_node_addr))
		return false;
	if (!xdr_sockaddr_tsm(xdrs, &objp->secondary_node_addr))
		return false;
	if (!xdr_bool(xdrs, &objp->has_primary))
		return false;
	if (!xdr_bool(xdrs, &objp->has_secondary))
		return false;
	if (!xdr_uint16_t(xdrs, &objp->ganesha_id))
		return false;
	if (!xdr_tsm_export_info(xdrs, &objp->export_info))
		return false;
	if (!xdr_bool(xdrs, &objp->reclaim))
		return false;
	return true;
}

bool xdr_tsm_rpc_states(XDR *xdrs, tsm_rpc_states *objp)
{
	if (!xdr_u_int(xdrs, &objp->tsmrec_len))
		return false;

	if (!xdr_array(xdrs, (char **)&objp->tsmarray_val, &objp->tsmrec_len,
		       XDR_ARRAY_MAXLEN, sizeof(tsm_rpc_info),
		       (xdrproc_t)xdr_tsm_rpc_info))
		return false;
	return true;
}
