/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TSM_H_RPCGEN
#define _TSM_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef int int32_t;

typedef u_int uint32_t;

typedef quad_t int64_t;

typedef u_quad_t uint64_t;

typedef enum {
    EXPORT_NO_IO = 0,
    EXPORT_IO_IN_PROGRESS,
} tsm_export_state_t;

typedef enum {
    EXPORT_REF_INC,
    EXPORT_REF_DEC
} tsm_export_event_t;

struct tsm_export_info {
    uint16_t export_id;
    uint16_t export_ref_count;
    bool export_tsm_enabled;
    tsm_export_state_t export_state;
    tsm_export_event_t export_event;
};
typedef struct tsm_export_info tsm_export_info;

struct tsm_state_open {
	uint32_t share_access;
	uint32_t share_deny;
	char owner_str[1024];
};
typedef struct tsm_state_open tsm_state_open;

struct tsm_state_lock {
	uint32_t type;
	uint64_t start;
	uint64_t length;
	char owner_str[1024];
};
typedef struct tsm_state_lock tsm_state_lock;

struct tsm_state_deleg {
    int sd_type;
    int sd_state;
    int share_access;
    int share_deny;
    char owner_str[1024];
};

typedef struct tsm_state_deleg tsm_state_deleg;

struct tsm_rpc_info {
	uint32_t msg_type;
	/* for ACK matching; 0 = no ACK expected */
	uint64_t msg_id;
	uint64_t fsid_maj;
	uint64_t fsid_min;
	uint64_t fileid;
	uint16_t rec_type;
	struct tsm_state_open open_info;
	struct tsm_state_lock lock_info;
	struct tsm_state_deleg deleg_info;
	struct tsm_export_info export_info;
	sockaddr_t source_addr;
	sockaddr_t primary_node_addr;
	sockaddr_t secondary_node_addr;
	bool_t has_primary;
	bool_t has_secondary;
	uint16_t ganesha_id;
	bool_t reclaim;
};
typedef struct tsm_rpc_info tsm_rpc_info;

struct tsm_rpc_states {
	u_int tsmrec_len;
	tsm_rpc_info *tsmarray_val;
};
typedef struct tsm_rpc_states tsm_rpc_states;


#define TSMPROG 100081
#define TSM_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define TSMPROC_NULL 0
extern  enum clnt_stat tsmproc_null_1(void *, CLIENT *);
extern  bool tsmproc_null_1_svc(void *, struct svc_req *);
#define TSMPROC_SEND_MSG 1
extern  enum clnt_stat tsmproc_send_msg_1(tsm_rpc_info , void *, CLIENT *);
extern  bool tsmproc_send_msg_1_svc(tsm_rpc_info , void *, struct svc_req *);
#define TSMPROC_SEND_STATES 2
extern  enum clnt_stat tsmproc_send_states_1(tsm_rpc_states , void *, CLIENT *);
extern  bool tsmproc_send_states_1_svc(tsm_rpc_states , void *, struct svc_req *);
extern int tsmprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define TSMPROC_NULL 0
extern  enum clnt_stat tsmproc_null_1();
extern  bool tsmproc_null_1_svc();
#define TSMPROC_SEND_MSG 1
extern  enum clnt_stat tsmproc_send_msg_1();
extern  bool tsmproc_send_msg_1_svc();
#define TSMPROC_SEND_STATES 2
extern  enum clnt_stat tsmproc_send_states_1();
extern  bool tsmproc_send_states_1_svc();
extern int tsmprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool xdr_tsm_state_open (XDR *, tsm_state_open*);
extern  bool xdr_tsm_state_lock (XDR *, tsm_state_lock*);
extern  bool xdr_tsm_rpc_info (XDR *, tsm_rpc_info*);
extern  bool xdr_tsm_rpc_states (XDR *, tsm_rpc_states*);

#else /* K&R C */
extern bool xdr_tsm_state_open ();
extern bool xdr_tsm_state_lock ();
extern bool xdr_tsm_rpc_info ();
extern bool xdr_tsm_rpc_states ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TSM_H_RPCGEN */
